export const O_EMPTY_BLOCK = {
  centreX: 0,
  centreY: 0,
  desc: [],
  descDown: [],
  descLeft: [],
  descRight: [],
  descUp: [],
  name: "the system's empty block",
  orientation: 0,
  width: 0,
  height: 0,
  x: 0,
  y: 0,
};
